# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: analysis-api
#   labels:
#     tier: msvc
#     component: backend
#     name: analysis-api
# spec:
#   selector:
#     name: analysis-api
#     component: backend
#     tier: msvc
#   ports:
#   - protocol: TCP
#     port: 5000
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: analysis-api
#   labels:
#     tier: msvc
#     name: analysis-api
#     component: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       tier: msvc
#       name: analysis-api
#       component: backend
#   template:
#     metadata:
#       labels:
#         tier: msvc
#         name: analysis-api
#         component: backend
#     spec:
#       containers:
#       - name: analysis-api
#         image: guitou-app/msvc-analysis-api
#         env:
#         - name: ENV
#           value: dev
#         - name: MONGODB_URI
#           valueFrom:
#             configMapKeyRef:
#               name: env-vars
#               key: MONGODB_URI
#         - name: MONGODB_DBNAME
#           value: guitou-analysis
