---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: generator-pv
  labels:
    name: generator-api
    tier: msvc
    component: backend  
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /minikube-host/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generator-pvc
  labels:
    name: generator-api
    tier: msvc
    component: backend  
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: generator-api
  labels:
    name: generator-api
    tier: msvc
    component: backend  
spec:
  selector:
    name: generator-api
    tier: msvc
    component: backend  
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-api
  labels:
    name: generator-api
    tier: msvc
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: generator-api
      tier: msvc
      component: backend
  template:
    metadata:
      labels:
        name: generator-api
        tier: msvc
        component: backend
    spec:
      containers:
      - name: generator-api
        image: guitou-app/msvc-generator-api
        # Must add readinessProbe because it can arrive that gRPC connection 
        # To Project API is not effective
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: PROJECT_GRPC_SERVER
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: PROJECT_GRPC_SERVER
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: env-vars
              key: MONGODB_URI
        - name: MONGODB_DBNAME
          value: guitou-generator
        - name: JWT_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: JWT_PUBLIC_KEY
        - name: GIT_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: GIT_AUTH_USERNAME
        - name: GIT_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: GIT_AUTH_PASSWORD
        - name: GIT_REPO_URL
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: GIT_REPO_URL
        volumeMounts:
        - mountPath: /app-generated
          name: msvc-app-folder
      volumes:
      - name: msvc-app-folder
        persistentVolumeClaim:
          claimName: generator-pvc

