apiVersion: v1
data:
  JWT_PRIVATE_KEY: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIG4wIBAAKCAYEA3LKUnsq5pjo7fXx9MeKuyrNOneR619o7sA5MG80TkT2LpsCr
    Kmhgw1pHXrMnSRgjBXwfywqFL+ZiV9+pcJskGQtDQhbu59C+QWRmrxihPZlYRbFY
    t2up5yAM8ocCf1Qanlh1k6ioXWd4xvja6lHDL9cU2jLT07ui9z0YcxC+hlH8qbIT
    AE6LuHFXKR1qt2A+GQMXa/J8IMIbeTKt3ueK0SGMEwihxGxBDtuWhWSg0B0aVL9w
    PXboT2qjZJErXXRtlQC2gIVfDwV8Kt8mTWdINouJmk/6KdmqaKL0PsgzbrxhPmac
    R2jFuPqOSg63vyLp5aeOnvpaOGp/3LqhYRae87BlG0evc+/jr60kj0pOepRWcy8I
    mUKkC0gnqVbl9EnBaiKAbvlTVVjKf+pThF0YacQztoLdW7a+13QnyPRWQTnZ6+tw
    dGC/9IqksZk4g+DfsOjNeoWahlfaxu3z3d2ZUA0JVbA5q3mwVvRDP1sP/XzSmp4P
    pir704erHOXE44utAgMBAAECggGBAKtMoTavO3HeeRZpbfMuc2U5z6eWFBM+fF2m
    e0SI5Msy7hY8LZ747UIz7HmArNl7NpOnSDYcsEwBkguKusWAZYBa0ZWWn1CnIUU4
    XMtDXsOlJnLRuH6FvpZ6thH44ONbsF1/Y6N8oVH+YixuM9z0IYAcfT7vfKM3XMJy
    VWvab0dqk6ZTZZQzYxeCQZjUEGTM+uYHFELhL59tik2EHJiLN6AjXcnYRVdkfwq9
    PhPDi159eFaXUNMkXCRoLPJ+Cx66onI3y3YUdqNVU56GfVhQUBooFijFDLo/NEzu
    zvk0kBO2Xjrki7GgTg9aYAi2frwChDJipHBrwkz14CfuWbtKOwNj/2p2MVBmeck9
    t6p68k3M44OYZP6zdY4NfH4UHUMdd1vHNCEKl+FsQb7GSSbrUk6trxDGilbG35RP
    lC1lMNaT7AKjuB2gqxlQFk6bB7bWSSjgoyDMBsFLc9gGyJf5D/f1OSHAY5YI+jfW
    NQnAhZ9P6KX1GklWpnNJpGhgaEcEMQKBwQD5w1UBz+mxFvbSi/npJlY/2GYMg60a
    cL7EK5U5jXftTP//nOwyFH+x1+SXXhH97JFgbxhg31bnTwfLFIJv6DcaRTS083i/
    dDTct7q3ACwD6WRlmDfVb2lJ9fPrGsYCPCq/RqKRLI+glmngRdxgf9zgrmFf/4od
    30lR9Wso0K61hWPQ60GgCTtXr7Js1ZLMz3SYV/VLjrhV8GgfWGf8htFOuxbSEOKi
    jhDEqsN6SDytb62RMaS/K/Wq3WzdpBWnsRcCgcEA4jVw4qhE9Dn5s0OX0G1FQFs/
    VGjt3c79ViSTI2hNMFtrtPCq60GiXkxlhT4greabkhb9oAohP0+fIhpi708vzDfS
    awLjMMUl+mWYquHQcq+b881oEhH5oBH+N9xJYMcEwUqgFaX9CatP4T9pFToWqppF
    kqeqTKv3GxbcXdKJjWmFwQ8QztzHS5J/nJZIFB8WRSVY7l6ooRVuKwsgMCltbsix
    HX4ZBUYhAbUczu39XcCmGroZn4II3eEuUE2UD3vbAoHAG4bqvItkry7fvy7MOWUP
    RnQcMy7kCjD45XgEN1afLBk7cbmi0pYtyLUJraEhjIHhN+amoi6bTl0Id9pn0duf
    DxcnivX2jetJ1DWvr3GmaDv147iWFsDzssIXwwatYhutfm1Th3qIzeMmAiDQ/BW7
    i0vM0Z7BYy9zzkOlLtdpGfp8mM8E6ZV649wqZxJW3pnSuOOg1lYBfP9FCodc1pkp
    QmseRcK0p8POl05WwwhpH5haYdE93hADQHStBfSKqnO7AoHAZtrTzEukpsPhtNAM
    LHoy3dNflVrspUljyZJx0MyxJEa9T5WKsdOzJ1tnYdFg/JF5tVB83BMfEPF8Mv56
    c8O2wQ20wHGcqeVKonMlmrV4mV0d9Ro1stm3fkAQLogcWUPE9rqe1ZkW2BmsBYhW
    mI9EFSh2b/uKpLggcJHRe1uqrcEIT0Mxak3a1JL1MVbnyTZlYuVbbW9fD3d2E15I
    sX10w8W/OuDGMa60fVlDkxeFd+aL4GU0F2IB9BlafKr5opy3AoHAIJfVwpAGP5Q4
    JUnFBV8C80R4miK17Gqko8iJU9i/E9LyHH+L7O8JKxaYhNlp7DwCUkcPYidwSpeP
    op64vz+eV/KLd17RTvOlJqNoWeLNUx8XaetLnVqMdXSsekTK/PjBSE45uVuw6SbS
    b0aYE8DB7YMs49aTmB5UMR2G3wl1fuhw65DMZORbSGFqAWXaMIUzk7a8aMcPSVIG
    bv6zSj4y9lD+5sbTO8a9oOjKzB3nXesMuW7zLyVi6B/8s4RucN3r
    -----END RSA PRIVATE KEY-----
  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA3LKUnsq5pjo7fXx9MeKu
    yrNOneR619o7sA5MG80TkT2LpsCrKmhgw1pHXrMnSRgjBXwfywqFL+ZiV9+pcJsk
    GQtDQhbu59C+QWRmrxihPZlYRbFYt2up5yAM8ocCf1Qanlh1k6ioXWd4xvja6lHD
    L9cU2jLT07ui9z0YcxC+hlH8qbITAE6LuHFXKR1qt2A+GQMXa/J8IMIbeTKt3ueK
    0SGMEwihxGxBDtuWhWSg0B0aVL9wPXboT2qjZJErXXRtlQC2gIVfDwV8Kt8mTWdI
    NouJmk/6KdmqaKL0PsgzbrxhPmacR2jFuPqOSg63vyLp5aeOnvpaOGp/3LqhYRae
    87BlG0evc+/jr60kj0pOepRWcy8ImUKkC0gnqVbl9EnBaiKAbvlTVVjKf+pThF0Y
    acQztoLdW7a+13QnyPRWQTnZ6+twdGC/9IqksZk4g+DfsOjNeoWahlfaxu3z3d2Z
    UA0JVbA5q3mwVvRDP1sP/XzSmp4Ppir704erHOXE44utAgMBAAE=
    -----END PUBLIC KEY-----
kind: ConfigMap
metadata:
  name: jwt-keys
